### ISSUE TITLE
Enforce chaining methods indent

### ISSUE THREAD

**Issue by valeriangalliat** [busbud/js-style-guide#4]
Currently all of these examples are linted as valid:

``` js
// Correct
foo()
  .bar()
  .baz();
```

``` js
// Bad
foo()
.bar()
.baz();
```

``` js
// Equally bad
foo()
    .bar()
    .baz();
```

**Comment by Chris911** [comment]
Is there an eslint rule for that?

**Comment by valeriangalliat** [comment]
Currently searching, @dustinblackman any idea?

**Comment by dustinblackman** [comment]
@valeriangalliat I haven't seen one, anything I find is people try to avoid throwing this error.
